### ISSUE TITLE
Can't display Mountpoint Correctly

### ISSUE THREAD

**Issue by Ayymoss** [RIKRUS/MOTD#1]
**Describe the bug**
Using `mountpoints=('/')` works, but `mountpoints=('/media' '/')` doesn't. 

I get error: 
```
root@PlexSrv-VM:~# update-motd
df: no file systems processed
/etc/update-motd.d/10-hdd-free: line 14: (*50)/100: syntax error: operand expected (error token is "*50)/100")
run-parts: /etc/update-motd.d/10-hdd-free exited with return code 1
ERROR: could not generate new MOTD
```

**Expected behavior**
Show remaining space left.

**Screenshots**
https://i.imgur.com/xLsOC6h.png

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.2

**Additional context**
I'm trying to get the space remaining of a mounted NFS share, but fails with above error. See screenshot for more information.

**Comment by beaconborn** [comment]
I never used NFS, but I’ll try

**Comment by beaconborn** [comment]
i tested and found where issue
`df -hl` shows only local mounted fs
in 12 line need change `df -hl` to `df -h`

**Comment by Ayymoss** [comment]
That worked! Thank you very much!

**Comment by beaconborn** [comment]
Happy to help you
If you are not send issue, I never know that problem
